apiVersion: apps/v1
kind: Deployment
metadata:
   name: my-jenkinsaks-deployment
   labels:
      app: java-app
spec:
   replicas: 3
   selector:
      matchLabels:
         app: java-app
   template:
      metadata:
         labels:
            app: java-app
      spec:
         containers:
          - name: my-java-app
            image: rahuldevops2603/jenkins-aks:tag
            imagePullPolicy: Always
            ports:
             - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
   name: jenkinsaks-app-svc
   labels:
      app: java-app
spec:
   type: LoadBalancer
   selector:
      app: java-app
   ports:
    - protocol: TCP
      port: 5000
      targetPort: 80
   